.pylint.ini
NiaPy/algorithms/__init__.py
NiaPy/algorithms/modified/__init__.py
NiaPy/algorithms/modified/hba.py
README.md
examples/run_hba.py

- add hba implementation
- add usage example
- add hba to list of featured algorithms in README.md
In .pylint.ini I disabled similarity checking, because of the hba and bat implementation similarity.

add hybrid bat algorithm implementation with example

---

NiaPy/algorithms/basic/fpa.py

- Initial version of basic flower pollination algorithm is included in this PR.
- Please add run examples.
- We should test this implementation carefully.
- In the future, we have to decide if we use Levy flights implementation from scipy.

adding flower pollination algorithm

---

NiaPy/__init__.py
NiaPy/benchmarks/__init__.py
NiaPy/benchmarks/rastrigin.py
NiaPy/benchmarks/rosenbrock.py
NiaPy/benchmarks/sphere.py
NiaPy/tests/test_fa.py

add benchmarks module

---

NiaPy/algorithms/basic/__init__.py
README.md
examples/run_fpa.py

- Add FPA usage example
- Add link to FPA example in README.md

add fpa example. update README.md with example.

---

LICENSE.md
Makefile
NiaPy/algorithms/basic/ba.py
NiaPy/algorithms/basic/de.py
NiaPy/algorithms/basic/fa.py
NiaPy/algorithms/basic/fpa.py
NiaPy/algorithms/modified/hba.py
NiaPy/benchmarks/__init__.py
NiaPy/benchmarks/griewank.py
NiaPy/benchmarks/rastrigin.py
NiaPy/benchmarks/rosenbrock.py
NiaPy/benchmarks/sphere.py
NiaPy/benchmarks/utility.py
examples/run_ba.py
examples/run_de.py
mkdocs.yml
setup.py

- add modified algorithm implementation to BA with usage of predefine benchmarks functions.

add modified algorithm implementation 

---

NiaPy/algorithms/basic/__init__.py
NiaPy/algorithms/basic/gwo.py

Grey wolf optimizer is added!
Validation must be conducted! More tests are required!

new algorithm

---

NiaPy/tests/test_ba.py
NiaPy/tests/test_de.py
NiaPy/tests/test_fpa.py
NiaPy/tests/test_hba.py
examples/run_ba.py
examples/run_de.py
examples/run_fa.py
examples/run_fpa.py
examples/run_hba.py

Add basic tests for de, fa, fpa, hba.

Basic tests

---

NiaPy/benchmarks/__init__.py
NiaPy/benchmarks/ackley.py
NiaPy/benchmarks/utility.py
examples/run_ba.py

Feature functions

---

NiaPy/benchmarks/__init__.py
NiaPy/benchmarks/ackley.py
NiaPy/benchmarks/schwefel.py
NiaPy/benchmarks/utility.py

new function added;
update of domain

Schwefel function

---

.pydocstyle.ini
NiaPy/benchmarks/ackley.py
NiaPy/benchmarks/schwefel.py

Functions description

---

NiaPy/benchmarks/sphere.py

fix bounds for sphere function

---

.pylint.ini
NiaPy/__init__.py
NiaPy/benchmarks/__init__.py
NiaPy/benchmarks/schwefel.py
NiaPy/benchmarks/utility.py
NiaPy/benchmarks/whitley.py
README.md
examples/run_de.py

- add Whitley function implementation
- add variations of Schwefel's functions implementations

add function implementations

---

NiaPy/benchmarks/schwefel.py
NiaPy/benchmarks/whitley.py

correction and description added

schwefel and whitley

---

NiaPy/algorithms/basic/pso.py

fix code style syntax

---

NiaPy/benchmarks/griewank.py
examples/run_de.py

Griewank function

---

NiaPy/benchmarks/rastrigin.py
NiaPy/benchmarks/rosenbrock.py
NiaPy/benchmarks/sphere.py

Feature functions2

---

.gitignore
NiaPy/__init__.py
NiaPy/benchmarks/utility.py
examples/run.py
examples/run_abc.py

- add runner fix
- add runner results export json

Runner export

---

NiaPy/__init__.py
Pipfile
Pipfile.lock
examples/run.py

add runner export to xlsx

---

NiaPy/algorithms/basic/fpa.py

functions comments will also be added
Comment for Flower pollination algorithm.

add comment of arguments for fpa.py

---

NiaPy/benchmarks/__init__.py
NiaPy/benchmarks/happyCat.py
NiaPy/benchmarks/utility.py
README.md
examples/run.py

Happy cat function added

---

NiaPy/__init__.py

fix latex export

---

NiaPy/benchmarks/__init__.py
NiaPy/benchmarks/ridge.py
NiaPy/benchmarks/utility.py
README.md
examples/run.py

Ridge function

---

NiaPy/benchmarks/__init__.py
NiaPy/benchmarks/chungReynolds.py
NiaPy/benchmarks/utility.py
README.md
examples/run.py

Chung reynolds function

---

NiaPy/benchmarks/__init__.py
NiaPy/benchmarks/csendes.py
NiaPy/benchmarks/utility.py
README.md
examples/run.py

Csendes function

---

NiaPy/benchmarks/__init__.py
NiaPy/benchmarks/pinter.py
NiaPy/benchmarks/utility.py
README.md
examples/run.py

Pinter function added

---

NiaPy/benchmarks/__init__.py
NiaPy/benchmarks/qing.py
NiaPy/benchmarks/utility.py
README.md
examples/run.py

Qing function added

---

NiaPy/benchmarks/__init__.py
NiaPy/benchmarks/salomon.py
NiaPy/benchmarks/utility.py
README.md
examples/run.py

Salomon function

---

NiaPy/benchmarks/__init__.py
NiaPy/benchmarks/schumerSteiglitz.py
NiaPy/benchmarks/utility.py
README.md
examples/run.py

Schumer Steiglitz Function

---

NiaPy/benchmarks/__init__.py
NiaPy/benchmarks/step.py
NiaPy/benchmarks/utility.py
README.md
examples/run.py

Step function

---

NiaPy/benchmarks/__init__.py
NiaPy/benchmarks/step.py
NiaPy/benchmarks/stepint.py
NiaPy/benchmarks/utility.py
README.md
examples/run.py

Stepint function added

---

NiaPy/benchmarks/__init__.py
NiaPy/benchmarks/sumSquares.py
NiaPy/benchmarks/utility.py
README.md
examples/run.py

Sum Squares added

---

NiaPy/benchmarks/__init__.py
NiaPy/benchmarks/styblinskiTang.py
NiaPy/benchmarks/utility.py
README.md
examples/run.py

Styblinski-Tang Function added

---

.github/begginers_guide.md
CONTRIBUTING.md

- add begginer's guide on how to contribute to project

Improved Docs

---

NiaPy/__init__.py

compatibility bugfixes

---

.readthedocs.yml
setup.py

- add readthedocs configuration

Readthedocs configuration

---

Makefile
docs/source/conf.py

fix issues

---

NiaPy/benchmarks/alpine.py
NiaPy/benchmarks/happyCat.py
NiaPy/benchmarks/qing.py
NiaPy/benchmarks/step.py
NiaPy/benchmarks/stepint.py
NiaPy/benchmarks/styblinskiTang.py
NiaPy/benchmarks/sumSquares.py
NiaPy/benchmarks/whitley.py

docs descriptions

---

NiaPy/benchmarks/happyCat.py
NiaPy/benchmarks/schumerSteiglitz.py
NiaPy/benchmarks/step.py
NiaPy/benchmarks/stepint.py
NiaPy/tests/test_benchmark_functions.py
examples/run_gwo.py

benchmark tests added

---

NiaPy/benchmarks/__init__.py
NiaPy/benchmarks/ackley.py
NiaPy/benchmarks/alpine.py
NiaPy/benchmarks/chungReynolds.py
NiaPy/benchmarks/csendes.py
NiaPy/benchmarks/griewank.py
NiaPy/benchmarks/happyCat.py
NiaPy/benchmarks/pinter.py
NiaPy/benchmarks/qing.py
NiaPy/benchmarks/quintic.py
NiaPy/benchmarks/rastrigin.py
NiaPy/benchmarks/ridge.py
NiaPy/benchmarks/rosenbrock.py
NiaPy/benchmarks/salomon.py
NiaPy/benchmarks/schumerSteiglitz.py
NiaPy/benchmarks/schwefel.py
NiaPy/benchmarks/sphere.py
NiaPy/benchmarks/step.py
NiaPy/benchmarks/stepint.py
NiaPy/benchmarks/styblinskiTang.py
NiaPy/benchmarks/sumSquares.py
NiaPy/benchmarks/whitley.py

latex documentation fixes

---

.pylint.ini
NiaPy/algorithms/basic/abc.py
NiaPy/algorithms/basic/ba.py
NiaPy/algorithms/basic/de.py
NiaPy/algorithms/basic/fa.py
NiaPy/algorithms/basic/fpa.py
NiaPy/algorithms/basic/ga.py
NiaPy/algorithms/basic/gwo.py
NiaPy/algorithms/basic/pso.py
NiaPy/algorithms/modified/hba.py
NiaPy/algorithms/modified/jde.py
NiaPy/benchmarks/utility.py

- refactor benchmark's utility class
- remove disable pylint's

Refactoring

---

NiaPy/algorithms/basic/cs.py

fix codestyle

---

docs/requirements.txt

fix docs build

---

.readthedocs.yml
NiaPy/tests/test_gwo.py

fix auto build docs

---

NiaPy/algorithms/basic/cs.py
NiaPy/tests/test_cs.py
examples/run_cs.py

I have already fixed some problems in CS. We still need more tests. It seems that results are not optimal.

Fixed some problems in CS

---

NiaPy/algorithms/basic/de.py
NiaPy/algorithms/basic/pso.py
NiaPy/algorithms/modified/jde.py

fix code style

---

NiaPy/algorithms/basic/cs.py
NiaPy/algorithms/basic/de.py
NiaPy/algorithms/basic/fa.py
NiaPy/algorithms/basic/fpa.py

documentation fix

---

NiaPy/algorithms/basic/ga.py
NiaPy/algorithms/basic/gwo.py
NiaPy/algorithms/basic/pso.py

algorithms documentation fix

---

NiaPy/algorithms/modified/hba.py
NiaPy/algorithms/modified/jde.py

algorithms docs fix

---

docs/source/getting_started.rst
examples/basic_customized_example.py
examples/basic_example.py

- add getting started guide to documentation

add getting started guide

---

NiaPy/algorithms/basic/cs.py

fix cs code style

---

NiaPy/algorithms/basic/cs.py
NiaPy/algorithms/basic/pso.py
examples/run_cs.py
examples/run_pso.py

Provide a general description of the code changes in your pull
request... were there any bugs you had fixed? If so, mention them. If
these bugs have open GitHub issues, be sure to tag them here as well,
to keep the conversation linked together.
If there's anything else that's important and relevant to your pull
request, mention that information here. This could include
benchmarks, or other information.
Thanks for contributing to NiaPy!

CS levy flight fix

---

NiaPy/algorithms/basic/cs.py
NiaPy/tests/test_cs.py

- fixing various code style problems

code style fixes

---

README.rst

fix README.rst

---

NiaPy/__init__.py
NiaPy/algorithms/basic/ga.py
NiaPy/algorithms/modified/jde.py

fix algorithms docs

---

paper/paper.md

Fix paper title

---

paper/paper.bib

dois added

---

README.md
README.rst

Refers to issue #119
- added user dependencies to README
- add link to detailed list of user and development

fix for issue #119

---

NiaPy/algorithms/basic/abc.py
NiaPy/algorithms/basic/ba.py
NiaPy/algorithms/basic/de.py
NiaPy/algorithms/basic/fa.py
NiaPy/algorithms/basic/fpa.py
NiaPy/algorithms/basic/ga.py
NiaPy/algorithms/basic/gwo.py
NiaPy/algorithms/basic/pso.py
NiaPy/algorithms/modified/hba.py
NiaPy/algorithms/modified/jde.py

Addressing issue #120 
- Documentation of methods added

Documentation added

---

paper/paper.bib
paper/paper.md

Adresses issues #121 and #122 
- fixing paper references
- add paragraph

reference Fix

---

README.md

Zenodo added

---

NiaPy/algorithms/basic/__init__.py
NiaPy/algorithms/basic/fa.py
NiaPy/algorithms/basic/fwa.py
NiaPy/tests/test_fwa.py

* Added fixes for dynamic fireworks algorithm
* Added dynamic fireworks algorithm with Gaussian operator.

Fixes and new algorithm

---

docs/requirements.txt

add docs dependency

---

NiaPy/algorithms/modified/hba.py

Fixed issue where worse solutions are accepted for Hybrid Bat Algorithm.
https://github.com/NiaOrg/NiaPy/issues/156

HBA - bugfix

---

NiaPy/algorithms/basic/__init__.py
NiaPy/algorithms/basic/mfo.py
README.md
examples/run_mfo.py

This is Moth Flame Optimization by Mirjalili, Seyedali. It has some usage among researchers and currently I have an assignment about it. Since I've used NiaPy before, I felt like contributing.
This is heavily influenced from https://github.com/7ossam81/EvoloPy and http://www.alimirjalili.com/MFO_download.html. Probably it is optimizable.
I've tried to use numpy functions instead of the native functions. It might have some incosistencies in terms of coding styles, I'm open for edits.

Moth Flame Optimization

---

NiaPy/algorithms/basic/mfo.py
NiaPy/tests/test_mfo.py
examples/run_mfo.py

New tests for MFO

---

NiaPy/algorithms/algorithm.py
NiaPy/algorithms/basic/abc.py
NiaPy/tests/test_algorithm.py
NiaPy/tests/test_jde.py
NiaPy/tests/test_mke.py
NiaPy/tests/test_utility.py
NiaPy/util/__init__.py
NiaPy/util/exception.py
NiaPy/util/utility.py

Added new stopping conditions. Added changes to the base interface.

Added stopping conditions

---

NiaPy/algorithms/algorithm.py
NiaPy/algorithms/basic/mke.py
NiaPy/util/utility.py
examples/stopping_criterions.py

* Fix for function evaluation stopping condition
* Fix for algorithm iterations / generations stopping condition
* Fix for reference value stopping conditions

Added fixes for stopping conditions

---

NiaPy/algorithms/basic/abc.py
NiaPy/algorithms/basic/ba.py
NiaPy/algorithms/basic/es.py
NiaPy/algorithms/basic/fpa.py
NiaPy/algorithms/basic/fwa.py
NiaPy/algorithms/basic/ga.py
NiaPy/algorithms/basic/gwo.py
NiaPy/algorithms/modified/hba.py
NiaPy/algorithms/other/hc.py
NiaPy/algorithms/other/mts.py
NiaPy/algorithms/other/nmm.py
NiaPy/algorithms/other/sa.py
NiaPy/algorithms/other/ts.py

* Added iterations counter to some of the algorithms

Added iterations counter to some of the algorithms

---

README.md
examples/run_foa.py

I added examples for FOA algorithm and updated the README.md file.

FOA examples added and README.md update

---

NiaPy/algorithms/basic/foa.py
NiaPy/util/utility.py

I fixed the bug in the FOA algorithm where getBest function returned age along with the individual's variables/dimensions. I also fixed the bug in utility.py's limitRepair function that set an individual's exceeded upper bound variable to a lower bound value instead of the upper bound value.

FOA tree aging and limitRepair bug fix.

---

.bumpversion.cfg
NiaPy/__init__.py
setup.py

Fix bump2version configuration

Fix bump2version

---

README.md
README.rst

Provide a general description of the code changes in your pull
request... were there any bugs you had fixed? If so, mention them. If
these bugs have open GitHub issues, be sure to tag them here as well,
to keep the conversation linked together.
If there's anything else that's important and relevant to your pull
request, mention that information here. This could include
benchmarks, or other information.
Thanks for contributing to NiaPy!

Installation instructions for Fedora users

---

docs/source/features.rst
docs/source/index.rst
docs/source/installation.rst

Documentation update

---

README.rst
setup.py

- fix build_description in setup.py
- update README.rst (for pypi)

Fix build description

---

README.md
docs/source/api/index.rst
docs/source/features.rst
docs/source/index.rst

reference added, small fixes

---

NiaPy/algorithms/basic/de.py
NiaPy/tests/test_algorithm.py
NiaPy/tests/test_benchmark_functions.py
NiaPy/tests/test_de.py

Fixed some errors shown at the tests cases studied at issues.
Proportional was not fed with correct data, as average was not calculated correctly when infinity values were present.
By the other hand, raising assertions were needed.
Thank you for letting me getting in touch with the project.

Fixing issues related to tests at infinity benchmark and NPAging DE.

---

NiaPy/algorithms/basic/fss.py

`np.float` is a deprecated alias

np.float is deprecated

---

NiaPy/algorithms/basic/bfoa.py

Fixed wrong function call which caused the run to break when an elimination and dispersal step happened.

BFOA quick fix

---

NiaPy/algorithms/algorithm.py
NiaPy/algorithms/basic/cro.py
NiaPy/algorithms/basic/de.py
NiaPy/algorithms/basic/es.py
NiaPy/algorithms/basic/fss.py
NiaPy/algorithms/basic/gsa.py
NiaPy/algorithms/basic/hho.py
NiaPy/algorithms/basic/hs.py
NiaPy/algorithms/basic/kh.py
NiaPy/algorithms/basic/mbo.py
NiaPy/algorithms/basic/mfo.py
NiaPy/algorithms/basic/pso.py
NiaPy/algorithms/basic/sca.py
NiaPy/algorithms/other/rs.py
NiaPy/tests/test_iter_gen_counters.py

Fixed bug in Algorithm.runYield

---

NiaPy/tests/test_sade.py
examples/run_all.bat
examples/run_all.sh
setup.py

- test_sade.py -> typos removed
- setup.py -> python 3.9 added to classifiers
- run all examples -> .sh and .bat file updated in order to work with Python 3

some nitpicks

---

NiaPy/algorithms/basic/hs.py

corrected reference URL for basic hs algorithm

---

niapy/task.py

Fixed import error.

---

Algorithms.md

Minor changes in Algorithms.md

Edit Algorithms.md

---

setup.py

niapy was successfully built under Python 3.10.

Add Python 3.10 tag

---

examples/run_cs.py
examples/run_fa.py
niapy/algorithms/basic/ba.py
niapy/algorithms/basic/bfo.py
niapy/algorithms/basic/cs.py
niapy/algorithms/basic/fa.py
niapy/algorithms/basic/fpa.py
niapy/tests/test_fa.py
niapy/tests/test_fpa.py

- Fixed the Bat Algorithm implementation
- Fixed Cuckoo Search implementation
- Fixed Firefly Algorithm implementation
- Fixed Flower Pollination Algorithm implementation
- Added missing info to BFO class docstring
- This PR fixes #341

Fix various algorithms

---

examples/maximization_example.py

The use of **OptimizationType.MAXIMIZATION** was omitted from this example.

Maximization example corrected

---

niapy/algorithms/basic/clonalg.py
niapy/tests/test_problem_functions.py

- Fix #364, as discussed in my comment.
- Added a reference to the original article to the docstring
- Fixed Alpine2 test failing
EDIT: Alpine2 problem test is failing. I cannot reproduce this locally, so I'm trying some fixes here. It's just an issue of float precision, there should be no issues with the function itself.

Fix clonalg implementation

---

.github/workflows/all_tests.yml
.github/workflows/main.yml
Pipfile
niapy/runner.py

Add incremental testing to main workflow supported with cache

Add incremental testing to main workflow supported with cache

---

setup.py

Removed newlines from package description. This should fix #371.

Fix setup error

---

README.md
README.rst

This pull requests append lines to READMEs for install NiaPy package for Arch Linux. Fixes #373

Add instructions for install from AUR

---

README.md
README.rst

NiaPy is now available also as a package for Alpine Linux.

Installation instructions for Alpine linux users

---

.github/workflows/main.yml
Pipfile
examples/callback.py
niapy/algorithms/algorithm.py
niapy/callbacks.py
niapy/problems/alpine.py
niapy/problems/griewank.py
niapy/problems/schwefel.py
niapy/tests/test_iter_gen_counters.py

- Added callback functionality (closes issue #401).
- Removed `run_task` and `iteration_generator` methods from the Algorithm class. All the functionality has now been moved directly to `Algorithm.run`.
- Replaced the deprecated numpy function `np.product` with `np.prod`
- Added before_run and after_run callbacks (could maybe be used for some setup / cleanup)
- Added a reference to the algorithm object in the Callback class.
Callbacks can be implemented by extending the `Callback` base class. They can be passed to an algorithm in a list like so:
```python
from niapy.callbacks import Callback
from niapy.algorithms.basic import BatAlgorithm
from niapy.task import Task
class PrintMeanFitness(Callback):
def __init__(self):
super().__init__()
def after_iteration(self, population, fitness, …
```

WIP: Add callbacks

---

docs/source/index.rst

Update index.rst | docs

---

CONTRIBUTE_NEW_ALGORITHM.md

This draft document summarizes the main instructions for contributing/adding a new algorithm to the niapy framework.

doc: CONTRIBUTE NEW ALGORITHM

---

CONTRIBUTE_NEW_ALGORITHM.md

Summary of changes:
1. Enhanced `CONTRIBUTE_NEW_ALGORITHM.md`.

CONTRIBUTE_NEW_ALGORITHM.md

---

CONTRIBUTING.md
README.md

- Introduced table of contents (`README.md`).
- Updated dependency versions to reflect the current state of the package (`CONTRIBUTING.md`).

README & development dependencies

---

niapy/algorithms/basic/abc.py

In the previous ABC code, only the individuals with biggest `trial` value is compared to `limit`, the other individuals whoes `trial` >= `limit` are skipped for update. 
Thanks for contributing to NiaPy!

fix: scout bee phrase of ABC
